### ISSUE TITLE
vcf_to_zarr problem on Windows

### ISSUE THREAD

**Issue by alimanfoo** [cggh/scikit-allel#202]
Original report via email:

> I wanted to try your scikit-allel and therefore followed your blog posting / tutorial here: http://alimanfoo.github.io/2018/04/09/selecting-variants.html
> 
> I downloaded the same dateset “ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz” as you used in your tutorial (downloaded it here: http://hgdownload.cse.ucsc.edu/gbdb/hg19/1000Genomes/phase3/ )
> 
> Furthermore I installed scikit-allel via   “ $ conda install -c conda-forge scikit-allel “ as described in the docs. Installation was successful. 
> 
> But when converting the VCF to Zarr via   allel.vcf_to_zarr() I get the following error:
> 

```
Traceback (most recent call last):

  File "test.py", line 7, in <module>
    allel.vcf_to_zarr('c:/test/ALL.chr15.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz', 'c:/test/ALL

.chr15.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.zarr', group='22', fields='*', log=sys.stdout, overwrit

e=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\allel\io\vcf_read.py", line 802, in vcf_to_zarr

    _zarr_store_chunk(root, keys, chunk)

  File "C:\ProgramData\Anaconda3\lib\site-packages\allel\io\vcf_read.py", line 692, in _zarr_store_chunk

    root[k].append(chunk[k], axis=0)

  File "C:\ProgramData\Anaconda3\lib\site-packages\zarr\core.py", line 2049, in append

    return self._write_op(self._append_nosync, data, axis=axis)

  File "C:\ProgramData\Anaconda3\lib\site-packages\zarr\core.py", line 1955, in _write_op

    return self._synchronized_op(f, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\zarr\core.py", line 1945, in _synchronized_op

    result = f(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\zarr\core.py", line 2063, in _append_nosync

    raise ValueError('shape of data to append is not compatible with the array; '

ValueError: shape of data to append is not compatible with the array; all dimensions must match except for the dimension being appended
```

User reports the same error does not occur when running on a Linux system, so suspect a Windows-specific bug.

**Comment by alimanfoo** [comment]
Closing this as a dup of #215.
